### ISSUE TITLE
Error in PID data format

### ISSUE THREAD

**Issue by grausof** [italia/eudi-wallet-it-pid-provider-android-sdk#2]
There seems to be an error in the format of the returned PID which differs from what is written in the [technical rules](https://italia.github.io/eudi-wallet-it-docs/en/pid-data-model.html#id1).

In particular in `verified_claims -> verification`  `camelCase` was used instead of `snake_case`. And also `_sd` must be a single array not a nested array.

```json
"verification": {
      "trustFramework": "eidas",
      "assuranceLevel": "high",
      "_sd": [
        [
          "egxkDO_BIANUr9WY4Z_WBXA73N6cb9uTMg0ZeOqpkI0"
        ]
      ]
    }
```

it should be
```json
"verification": {
      "trust_framework": "eidas",
      "assurance_level": "high",
      "_sd": [
          "egxkDO_BIANUr9WY4Z_WBXA73N6cb9uTMg0ZeOqpkI0"
      ]
    }
```

Furthermore, the mandatory fields are not present in the header: `kid` and `trust_chain`

**Comment by grausof** [comment]
I would like to point out that there is also an error in the claim `evidence`:

```json
["rc44gvQS-S41EP8RUMitTQ","evidence",{"_sd":["egxkDO_BIANUr9WY4Z_WBXA73N6cb9uTMg0ZeOqpkI0"]}]
```
must be an array
```json
["rc44gvQS-S41EP8RUMitTQ","evidence",[...]]
```
and the content as defined in the technical rules. 

So I expect:
```json
["rc44gvQS-S41EP8RUMitTQ","evidence",[{"type": "electronic_record", "record": {"type": "eidas.it.cie", "source": {"organization_name": "Ministero dell'Interno", "organization_id": "m_it", "country_code": "IT"}}}]]
```

**Comment by grausof** [comment]
Another error in date format

```json
["fuNp97Hf3wV6y48y-QZhIg","birthdate","10-01-1980"]
```
should be:
```json
["fuNp97Hf3wV6y48y-QZhIg","birthdate","1980-10-01"]
```

Refs: https://openid.net/specs/openid-connect-core-1_0.html

**Comment by fventola-ipzs** [comment]
This issue is not in the correct repository, the PID data format is issued by the backend, open it there.
