### ISSUE TITLE
Wrong pushed authorization request (PAR)

### ISSUE THREAD

**Issue by grausof** [italia/eudi-wallet-it-pid-provider-android-sdk#4]
Analyzing the technical specifications and what the SDK has done, it seems that there are some inconsistencies.
This is the `signedJwtForPar` that the SDK generates: 
```
eyJraWQiOiI3Ny05YU8tX3ZlLV92Ump2djcxcGJ1LV92VllkY25MdnY3MWdRTy1fdmUtX3ZlLV92ZS1fdlh2dnY3MGs3Ny05NzctOWJ1LV92VE5iNzctOVUtLV92USIsImFsZyI6IkVTMjU2In0.eyJjbGllbnRfYXNzZXJ0aW9uX3R5cGUiOiJ1cm46aWV0ZjpwYXJhbXM6b2F1dGg6Y2xpZW50LWFzc2VydGlvbi10eXBlOmp3dC1iZWFyZXIiLCJhdXRob3JpemF0aW9uX2RldGFpbHMiOiJ7XCJ0eXBlXCI6XCJ0eXBlXCIsXCJmb3JtYXRcIjpcInZjK3NkLWp3dFwiLFwiY3JlZGVudGlhbF9kZWZpbml0aW9uXCI6e1wiY2xhaW1cIjpcImV1LmV1ZGl3LnBpZC5pdFwifX0iLCJyZXNwb25zZV90eXBlIjoiY29kZSIsImNvZGVfY2hhbGxlbmdlX21ldGhvZCI6InMyNTYiLCJyZWRpcmVjdF91cmkiOiJodHRwczovL3d3dy5nb29nbGUuY29tIiwic3RhdGUiOiJmNDE2ZmMwZS01MjNhLTRjNGItYjYyNC0xOWNjNGNmMTljY2MiLCJjbGllbnRfYXNzZXJ0aW9uIjoie1xuICBcImlzc1wiOiBcImh0dHBzOi8vd2FsbGV0LXByb3ZpZGVyLmV4YW1wbGUub3JnXCIsXG4gIFwic3ViXCI6IFwidGh1bXByaW50LW9mLXRoZS1qd2staW4tdGhlLWNuZi1pZGVudGlmaXlpbmctdGhlLXdhbGxldFwiLFxuICBcImlhdFwiOiAxNjY1MTM3OTExLFxuICBcImV4cFwiOiAxNjY1MTM4OTExLFxuICBcInR5cGVcIjogXCJXYWxsZXRJbnN0YW5jZUF0dGVzdGF0aW9uXCIsXG4gIFwic3VwcG9ydGVkX0xvQVwiOiBcImhpZ2hcIixcbiAgXCJwb2xpY3lfdXJpXCI6IFwiaHR0cHM6Ly93YWxsZXQtcHJvdmlkZXIuZXhhbXBsZS5jb20vcHJpdmFjeV9wb2xpY3lcIixcbiAgXCJ0b3NfdXJpXCI6IFwiaHR0cHM6Ly93YWxsZXQtcHJvdmlkZXIuZXhhbXBsZS5jb20vaW5mb19wb2xpY3lcIixcbiAgXCJsb2dvX3VyaVwiOiBcImh0dHBzOi8vd2FsbGV0LXByb3ZpZGVyLmV4YW1wbGUuY29tL3NnZC1jbXlrLTE1MGRwaS05MG1tLnN2Z1wiLFxuICBcImNuZlwiOiB7XG4gICAgXCJqd2tcIjoge1xuICAgICAgICBcImt0eVwiOiBcIkVDXCIsXG4gICAgICAgIFwia2lkXCI6IFwid2FsbGV0LXB1Yi1qd2sta2lkXCIsXG4gICAgICAgIFwiY3J2XCI6IFwiUC0yNTZcIixcbiAgICAgICAgXCJ4XCI6IFwiYTFNZFRib1NVYnE0U094NExtaE9JMkFld1ZrWldEUUQwZ1A5bk9pU25IVVwiLFxuICAgICAgICBcInlcIjogXCJmOG4xSWdwZllPQkZaTTBLeGtUZDBONVkyUC1JTk5tVV82Uy1nRHJvX0ZFXCJcbiAgIH1cbiAgfVxufVxuIiwiY2xpZW50X2lkIjoi77-9aO-_ve-_vVx1MDAxOO-_vWlu77-9Vlx1MDAxRHJy77-9YEDvv73vv73vv73vv71777-9JO-_ve-_vW7vv70zW--_vVPvv70iLCJjb2RlX2NoYWxsZW5nZSI6IjJ5d3VjdzFrZWRTb1hXWlRjcVRUeG1KNkpiR3c4djlvckt5bnVQUlR5bncifQ.vbVVfe8fcuLUaLTa8tqDJTP5Xmf8ODLdotSiR2SkzoRG8y-Epn7PVvqydaN4mL0GGSUis4yXo1r4SqnjupSxow
```

and going to decode it with [jwt.io](https://jwt.io/#debugger-io?token=eyJraWQiOiI3Ny05YU8tX3ZlLV92Ump2djcxcGJ1LV92VllkY25MdnY3MWdRTy1fdmUtX3ZlLV92ZS1fdlh2dnY3MGs3Ny05NzctOWJ1LV92VE5iNzctOVUtLV92USIsImFsZyI6IkVTMjU2In0.eyJjbGllbnRfYXNzZXJ0aW9uX3R5cGUiOiJ1cm46aWV0ZjpwYXJhbXM6b2F1dGg6Y2xpZW50LWFzc2VydGlvbi10eXBlOmp3dC1iZWFyZXIiLCJhdXRob3JpemF0aW9uX2RldGFpbHMiOiJ7XCJ0eXBlXCI6XCJ0eXBlXCIsXCJmb3JtYXRcIjpcInZjK3NkLWp3dFwiLFwiY3JlZGVudGlhbF9kZWZpbml0aW9uXCI6e1wiY2xhaW1cIjpcImV1LmV1ZGl3LnBpZC5pdFwifX0iLCJyZXNwb25zZV90eXBlIjoiY29kZSIsImNvZGVfY2hhbGxlbmdlX21ldGhvZCI6InMyNTYiLCJyZWRpcmVjdF91cmkiOiJodHRwczovL3d3dy5nb29nbGUuY29tIiwic3RhdGUiOiJmNDE2ZmMwZS01MjNhLTRjNGItYjYyNC0xOWNjNGNmMTljY2MiLCJjbGllbnRfYXNzZXJ0aW9uIjoie1xuICBcImlzc1wiOiBcImh0dHBzOi8vd2FsbGV0LXByb3ZpZGVyLmV4YW1wbGUub3JnXCIsXG4gIFwic3ViXCI6IFwidGh1bXByaW50LW9mLXRoZS1qd2staW4tdGhlLWNuZi1pZGVudGlmaXlpbmctdGhlLXdhbGxldFwiLFxuICBcImlhdFwiOiAxNjY1MTM3OTExLFxuICBcImV4cFwiOiAxNjY1MTM4OTExLFxuICBcInR5cGVcIjogXCJXYWxsZXRJbnN0YW5jZUF0dGVzdGF0aW9uXCIsXG4gIFwic3VwcG9ydGVkX0xvQVwiOiBcImhpZ2hcIixcbiAgXCJwb2xpY3lfdXJpXCI6IFwiaHR0cHM6Ly93YWxsZXQtcHJvdmlkZXIuZXhhbXBsZS5jb20vcHJpdmFjeV9wb2xpY3lcIixcbiAgXCJ0b3NfdXJpXCI6IFwiaHR0cHM6Ly93YWxsZXQtcHJvdmlkZXIuZXhhbXBsZS5jb20vaW5mb19wb2xpY3lcIixcbiAgXCJsb2dvX3VyaVwiOiBcImh0dHBzOi8vd2FsbGV0LXByb3ZpZGVyLmV4YW1wbGUuY29tL3NnZC1jbXlrLTE1MGRwaS05MG1tLnN2Z1wiLFxuICBcImNuZlwiOiB7XG4gICAgXCJqd2tcIjoge1xuICAgICAgICBcImt0eVwiOiBcIkVDXCIsXG4gICAgICAgIFwia2lkXCI6IFwid2FsbGV0LXB1Yi1qd2sta2lkXCIsXG4gICAgICAgIFwiY3J2XCI6IFwiUC0yNTZcIixcbiAgICAgICAgXCJ4XCI6IFwiYTFNZFRib1NVYnE0U094NExtaE9JMkFld1ZrWldEUUQwZ1A5bk9pU25IVVwiLFxuICAgICAgICBcInlcIjogXCJmOG4xSWdwZllPQkZaTTBLeGtUZDBONVkyUC1JTk5tVV82Uy1nRHJvX0ZFXCJcbiAgIH1cbiAgfVxufVxuIiwiY2xpZW50X2lkIjoi77-9aO-_ve-_vVx1MDAxOO-_vWlu77-9Vlx1MDAxRHJy77-9YEDvv73vv73vv73vv71777-9JO-_ve-_vW7vv70zW--_vVPvv70iLCJjb2RlX2NoYWxsZW5nZSI6IjJ5d3VjdzFrZWRTb1hXWlRjcVRUeG1KNkpiR3c4djlvckt5bnVQUlR5bncifQ.vbVVfe8fcuLUaLTa8tqDJTP5Xmf8ODLdotSiR2SkzoRG8y-Epn7PVvqydaN4mL0GGSUis4yXo1r4SqnjupSxow) you may notice that there is a problem with the `authorization details` attribute as it has not been encoded correctly and therefore does not result in valid JSON.

Currently the format is this
```json
"authorization_details": "{\"type\":\"type\",\"format\":\"vc+sd-jwt\",\"credential_definition\":{\"claim\":\"eu.eudiw.pid.it\"}}"
```
But I expect something like this:
```json
"authorization_details":[
{
    "type":"openid_credential",
    "format": "vc+sd-jwt",
    "credential_definition": {
        "type": ["eu.eudiw.pid.it"]
    }
}
]
```

Furthermore, there is a double error regarding the Wallet Instance Attestation:
From technical specifications it must be sent as a parameter of the POST request towards /as/par

```js
POST /as/par HTTP/1.1
Host: pid-provider.example.org
Content-Type: application/x-www-form-urlencoded

response_type=code
&client_id=$thumprint-of-the-jwk-in-the-cnf-wallet-attestation$
&code_challenge=E9Melhoa2OwvFrEMTJguCHaoeK1t8URWbuGJSstw-cM
&code_challenge_method=S256
&request=eyJhbGciOiJSUzI1NiIsImtpZCI6ImsyYmRjIn0.ew0KICJpc3MiOiAiczZCaGRSa3F0MyIsDQogImF1ZCI6ICJodHRwczovL3NlcnZlci5leGFtcGxlLmNvbSIsDQo gInJlc3BvbnNlX3R5cGUiOiAiY29kZSBpZF90b2tlbiIsDQogImNsaWVudF9pZCI6ICJzNkJoZFJrcXQzIiwNCiAicmVkaXJlY3RfdXJpIjogImh0dHBzOi8vY2xpZW50LmV4YW1...
&client_assertion_type=urn:ietf:params:oauth:client-assertion-type:jwt-key-attestation
&client_assertion=$WalletInstanceAttestation$
```
and need not be contained within the JWT. The `client_assertion` parameter is from the request not the `signedJwtForPar`.

However, the Wallet Instance Attestation is wrong. Seeing your code the WIA is passed as a JSON:
```json
"client_assertion": "{\n  \"iss\": \"https://wallet-provider.example.org\",\n  \"sub\": \"thumprint-of-the-jwk-in-the-cnf-identifiying-the-wallet\",\n  \"iat\": 1665137911,\n  \"exp\": 1665138911,\.....
```
but the Wallet Instance Attestation is a signed JWT so it must be a string not the JSON converted to string.

Please, I ask you to fix these things as soon as possible in order to allow us a correct integration.
Thanks!

CC: @fmarino-ipzs @fventola-ipzs @peppelinux

**Comment by sviluppo-ipzs** [comment]
Fixed in version 1.1.1.
