### ISSUE TITLE
SDK interface inconsistency

### ISSUE THREAD

**Issue by hevelius** [italia/eudi-wallet-it-pid-provider-android-sdk#5]
To our understanding, the **AndroidPidProvider SDK** was anticipated to mirror the existing interface provided by the **io-cie-sdk** implementation, which can be found at this link: https://github.com/pagopa/io-cie-sdk/blob/master/index.js. This interface contains the methods leveraged by io application to achieve a login process with CIE.

This alignment was essential as our designer had already utilized the existing cie authentication flow to create the UI/UX. However, upon inspection, we observed that the AndroidPidProvider SDK **exposes two distinct methods**, namely **Initialize()** and **StartAuthFlow()**, which rely on an **_underlying implementation_** of cieidsdk.

<img src="https://github.com/italia/eudi-wallet-it-pid-provider-android-sdk/assets/49342144/463e8701-b2bf-4be9-9eb7-3fc9d0b1e9a9" height="400px"/>

<img src="https://github.com/italia/eudi-wallet-it-pid-provider-android-sdk/assets/49342144/1a4b64ef-63a2-4038-88cb-74fdd432d654" height="400px"/>

This deviation from the expected interface poses challenges in seamlessly integrating the SDK with React Native. The disparity in the interface not only impedes the bridging process to React Native but also complicates the management of the UI due to the background operation of the bridge, which relies on native method calls and their callbacks for UI manipulation.

To address this issue effectively, we request that the AndroidPidProvider SDK to be adjusted to align its interface with the existing io-cie-sdk implementation. We can then ensure a React Native integration by maintain consistency in the UI/UX design created by our designer.

**Comment by sviluppo-ipzs** [comment]
Fixed in version 1.1.1.
