### ISSUE TITLE
Missed `CieIDSdk.start(this, this)`

### ISSUE THREAD

**Issue by hevelius** [italia/eudi-wallet-it-pid-provider-android-sdk#6]
Probably missed `CieIDSdk.start(this, this)` in MainDemoActivity.kt. The NFCReader appear without read NFC tag.

**Comment by hevelius** [comment]
I tried to add `CieIDSdk.start(this, this)` in onCreate just after startSDKFlow
```kotlin
override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        startSDKFlow()
        CieIDSdk.start(this, this)
    }
```
Now NFC works but returns the error
onError: Check del tag fallito

**Comment by fventola-ipzs** [comment]
Is commented in the code, we will fix it ASAP.

**Comment by sviluppo-ipzs** [comment]
Fixed in v.1.1.1
